dist: xenial
os: linux
language: c
compiler: gcc
addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - cmake
      - python3.8
script:
  - sudo rm -f /usr/bin/gcc /usr/bin/gcov /usr/bin/python
  - sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
  - sudo ln -s /usr/bin/gcov-9 /usr/bin/gcov
  - sudo ln -s /usr/bin/python3.8 /usr/bin/python
  - gcc --version
  - gcov --version
  - python --version
  - python autogen.py -e -b -cv -r -nf -nt
after_success:
  - bash <(curl -s https://codecov.io/bash)
